# Generated by Django 3.0.6 on 2020-05-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision', models.CharField(max_length=100)),
                ('nombreClave', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('fechaActivada', models.DateField(auto_now=True)),
                ('lugar', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'misiones',
            },
        ),
    ]
